{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  labels:
{{ include "microservice.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}

